### ISSUE TITLE
Software Factory Output - Poor error shows when a Domain operation's parameter's type is unconfigured

### ISSUE THREAD

**Issue by JonathanLydall** [IntentSoftware/IntentArchitect#105]
For example, something like this:

![image](https://user-images.githubusercontent.com/1290262/36587040-8870116c-188c-11e8-98f1-fbdf98bc18f5.png)

The problem is that the error you see in the software factory does not help you work out where the problem lies, it is something like:

```System.ArgumentNullException occurred
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: key
  ParamName=key
  Source=mscorlib
  StackTrace:
       at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
       at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
       at Intent.IArchitect.Agent.Persistence.Dsl.UmlModelBoundedContextLoader.GetTypeName(String typeId, ModelType& modelType)
  InnerException: 
```

At least the first, but ideally both of these improvements should be made:
- Present the error in such a way the user can solve the problem, for example by including things like the App name, DSL name, class name, operation name, etc.
- Put some sort of visual indicator on the UML DSL that there is a problem, like on the services DTO when a type is missing.

**Comment by JonathanLydall** [comment]
Already done 52551c61f7fc0b587759d932f93641f96aa82d3b which improves the error description.
